///////////////////////////////////////////////////////////
//  DBForbidden.cs
//  Implementation of the Class DBForbidden
//  Generated by Enterprise Architect
//  Created on:      05-七月-2011 16:33:34
//  Original author: Administrator
///////////////////////////////////////////////////////////




using Kt.Framework.User.Forbidden;
namespace Kt.Framework.User.Forbidden
{
    /// <summary>
    /// 本方法用于与数据库结合，暂不实现
    /// </summary>
    public class DBForbidden : IForbidden
    {

        public DBForbidden()
        {

        }



        public virtual void Dispose()
        {

        }

        /// <summary>
        /// 从列表中排除
        /// </summary>
        /// <param name="UserForbiddenModel">从队列中排除</param>
        public void DeList(UserForbiddenModel UserForbiddenModel)
        {

        }

        /// <summary>
        /// 加入列表
        /// </summary>
        /// <param name="UserForbiddenModel"></param>
        public void EnList(UserForbiddenModel UserForbiddenModel)
        {

        }

        /// 
        /// <param name="Uid"></param>
        public bool IsForbidden(decimal Uid)
        {

            return false;
        }

        public void ClearForbiddenList(decimal uid)
        { 
            
        }

    }//end DBForbidden

}//end namespace Forbidden