///////////////////////////////////////////////////////////
//  UserForbiddenModel.cs
//  Implementation of the Class UserForbiddenModel
//  Generated by Enterprise Architect
//  Created on:      05-七月-2011 9:51:49
//  Original author: 张保维
///////////////////////////////////////////////////////////




using System;
namespace Kt.Framework.User.Forbidden
{
    public class UserForbiddenModel
    {

        /// <summary>
        /// 最后一次登录错误时间
        /// </summary>
        private DateTime _LastTime;
        private decimal _Uid;
        private int _ErrorCount;



        public UserForbiddenModel()
        {

        }




        public int ErrorCount
        {
            get
            {
                return _ErrorCount;
            }
            set
            {
                _ErrorCount = value;
            }
        }

        /// <summary>
        /// 最后一次登录错误时间
        /// </summary>
        public DateTime LastTime
        {
            get
            {
                return _LastTime;
            }
            set
            {
                _LastTime = value;
            }
        }

        public decimal Uid
        {
            get
            {
                return _Uid;
            }
            set
            {
                _Uid = value;
            }
        }

    }//end UserForbiddenModel

}//end namespace Forbidden