//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kt.GameGroup.Services.CharRoomService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int rIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rPswField;
        
        private System.Nullable<int> rNowNumField;
        
        private System.Nullable<int> rMaxNumField;
        
        private System.Nullable<short> rOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rTypeField;
        
        private System.Nullable<int> gIdField;
        
        private System.Nullable<int> fIdField;
        
        private System.Nullable<int> rMemberTypeField;
        
        private System.Nullable<int> rMicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rMicTimeField;
        
        private System.Nullable<int> rTextChatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rChatSpeedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rTextWordsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int rId {
            get {
                return this.rIdField;
            }
            set {
                if ((this.rIdField.Equals(value) != true)) {
                    this.rIdField = value;
                    this.RaisePropertyChanged("rId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rName {
            get {
                return this.rNameField;
            }
            set {
                if ((object.ReferenceEquals(this.rNameField, value) != true)) {
                    this.rNameField = value;
                    this.RaisePropertyChanged("rName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string rPsw {
            get {
                return this.rPswField;
            }
            set {
                if ((object.ReferenceEquals(this.rPswField, value) != true)) {
                    this.rPswField = value;
                    this.RaisePropertyChanged("rPsw");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> rNowNum {
            get {
                return this.rNowNumField;
            }
            set {
                if ((this.rNowNumField.Equals(value) != true)) {
                    this.rNowNumField = value;
                    this.RaisePropertyChanged("rNowNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> rMaxNum {
            get {
                return this.rMaxNumField;
            }
            set {
                if ((this.rMaxNumField.Equals(value) != true)) {
                    this.rMaxNumField = value;
                    this.RaisePropertyChanged("rMaxNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<short> rOrder {
            get {
                return this.rOrderField;
            }
            set {
                if ((this.rOrderField.Equals(value) != true)) {
                    this.rOrderField = value;
                    this.RaisePropertyChanged("rOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string rMode {
            get {
                return this.rModeField;
            }
            set {
                if ((object.ReferenceEquals(this.rModeField, value) != true)) {
                    this.rModeField = value;
                    this.RaisePropertyChanged("rMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string rType {
            get {
                return this.rTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.rTypeField, value) != true)) {
                    this.rTypeField = value;
                    this.RaisePropertyChanged("rType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> gId {
            get {
                return this.gIdField;
            }
            set {
                if ((this.gIdField.Equals(value) != true)) {
                    this.gIdField = value;
                    this.RaisePropertyChanged("gId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> fId {
            get {
                return this.fIdField;
            }
            set {
                if ((this.fIdField.Equals(value) != true)) {
                    this.fIdField = value;
                    this.RaisePropertyChanged("fId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> rMemberType {
            get {
                return this.rMemberTypeField;
            }
            set {
                if ((this.rMemberTypeField.Equals(value) != true)) {
                    this.rMemberTypeField = value;
                    this.RaisePropertyChanged("rMemberType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> rMic {
            get {
                return this.rMicField;
            }
            set {
                if ((this.rMicField.Equals(value) != true)) {
                    this.rMicField = value;
                    this.RaisePropertyChanged("rMic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string rMicTime {
            get {
                return this.rMicTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.rMicTimeField, value) != true)) {
                    this.rMicTimeField = value;
                    this.RaisePropertyChanged("rMicTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> rTextChat {
            get {
                return this.rTextChatField;
            }
            set {
                if ((this.rTextChatField.Equals(value) != true)) {
                    this.rTextChatField = value;
                    this.RaisePropertyChanged("rTextChat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string rChatSpeed {
            get {
                return this.rChatSpeedField;
            }
            set {
                if ((object.ReferenceEquals(this.rChatSpeedField, value) != true)) {
                    this.rChatSpeedField = value;
                    this.RaisePropertyChanged("rChatSpeed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string rTextWords {
            get {
                return this.rTextWordsField;
            }
            set {
                if ((object.ReferenceEquals(this.rTextWordsField, value) != true)) {
                    this.rTextWordsField = value;
                    this.RaisePropertyChanged("rTextWords");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CharRoomService.gameServiceSoap")]
    public interface gameServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 gid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addRoom", ReplyAction="*")]
        Kt.GameGroup.Services.CharRoomService.addRoomResponse addRoom(Kt.GameGroup.Services.CharRoomService.addRoomRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 rid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteRoom", ReplyAction="*")]
        Kt.GameGroup.Services.CharRoomService.deleteRoomResponse deleteRoom(Kt.GameGroup.Services.CharRoomService.deleteRoomRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 rid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRoom", ReplyAction="*")]
        Kt.GameGroup.Services.CharRoomService.updateRoomResponse updateRoom(Kt.GameGroup.Services.CharRoomService.updateRoomRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 rid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateRoomInfo", ReplyAction="*")]
        Kt.GameGroup.Services.CharRoomService.updateRoomInfoResponse updateRoomInfo(Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 rid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectRoom", ReplyAction="*")]
        Kt.GameGroup.Services.CharRoomService.selectRoomResponse selectRoom(Kt.GameGroup.Services.CharRoomService.selectRoomRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 gid 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/selectRoomByfId", ReplyAction="*")]
        Kt.GameGroup.Services.CharRoomService.selectRoomByfIdResponse selectRoomByfId(Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addRoom", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.addRoomRequestBody Body;
        
        public addRoomRequest() {
        }
        
        public addRoomRequest(Kt.GameGroup.Services.CharRoomService.addRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rpsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rmaxnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string rorder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string rmode;
        
        public addRoomRequestBody() {
        }
        
        public addRoomRequestBody(string gid, string fid, string rname, string rpsw, string rmaxnum, string rtype, string rorder, string rmode) {
            this.gid = gid;
            this.fid = fid;
            this.rname = rname;
            this.rpsw = rpsw;
            this.rmaxnum = rmaxnum;
            this.rtype = rtype;
            this.rorder = rorder;
            this.rmode = rmode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.addRoomResponseBody Body;
        
        public addRoomResponse() {
        }
        
        public addRoomResponse(Kt.GameGroup.Services.CharRoomService.addRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int addRoomResult;
        
        public addRoomResponseBody() {
        }
        
        public addRoomResponseBody(int addRoomResult) {
            this.addRoomResult = addRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteRoom", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.deleteRoomRequestBody Body;
        
        public deleteRoomRequest() {
        }
        
        public deleteRoomRequest(Kt.GameGroup.Services.CharRoomService.deleteRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rid;
        
        public deleteRoomRequestBody() {
        }
        
        public deleteRoomRequestBody(string rid) {
            this.rid = rid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.deleteRoomResponseBody Body;
        
        public deleteRoomResponse() {
        }
        
        public deleteRoomResponse(Kt.GameGroup.Services.CharRoomService.deleteRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class deleteRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int deleteRoomResult;
        
        public deleteRoomResponseBody() {
        }
        
        public deleteRoomResponseBody(int deleteRoomResult) {
            this.deleteRoomResult = deleteRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateRoom", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.updateRoomRequestBody Body;
        
        public updateRoomRequest() {
        }
        
        public updateRoomRequest(Kt.GameGroup.Services.CharRoomService.updateRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rpsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rmaxnum;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rtype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rorder;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rmode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string rname;
        
        public updateRoomRequestBody() {
        }
        
        public updateRoomRequestBody(string rid, string rpsw, string rmaxnum, string rtype, string rorder, string rmode, string rname) {
            this.rid = rid;
            this.rpsw = rpsw;
            this.rmaxnum = rmaxnum;
            this.rtype = rtype;
            this.rorder = rorder;
            this.rmode = rmode;
            this.rname = rname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.updateRoomResponseBody Body;
        
        public updateRoomResponse() {
        }
        
        public updateRoomResponse(Kt.GameGroup.Services.CharRoomService.updateRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updateRoomResult;
        
        public updateRoomResponseBody() {
        }
        
        public updateRoomResponseBody(int updateRoomResult) {
            this.updateRoomResult = updateRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRoomInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateRoomInfo", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequestBody Body;
        
        public updateRoomInfoRequest() {
        }
        
        public updateRoomInfoRequest(Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRoomInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rpsw;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string rname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string rmembertype;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string rmic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string rmictime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string rtextchat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string rchatspeed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string rtextwords;
        
        public updateRoomInfoRequestBody() {
        }
        
        public updateRoomInfoRequestBody(string rid, string rpsw, string rname, string rmembertype, string rmic, string rmictime, string rtextchat, string rchatspeed, string rtextwords) {
            this.rid = rid;
            this.rpsw = rpsw;
            this.rname = rname;
            this.rmembertype = rmembertype;
            this.rmic = rmic;
            this.rmictime = rmictime;
            this.rtextchat = rtextchat;
            this.rchatspeed = rchatspeed;
            this.rtextwords = rtextwords;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRoomInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateRoomInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.updateRoomInfoResponseBody Body;
        
        public updateRoomInfoResponse() {
        }
        
        public updateRoomInfoResponse(Kt.GameGroup.Services.CharRoomService.updateRoomInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRoomInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int updateRoomInfoResult;
        
        public updateRoomInfoResponseBody() {
        }
        
        public updateRoomInfoResponseBody(int updateRoomInfoResult) {
            this.updateRoomInfoResult = updateRoomInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectRoomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectRoom", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.selectRoomRequestBody Body;
        
        public selectRoomRequest() {
        }
        
        public selectRoomRequest(Kt.GameGroup.Services.CharRoomService.selectRoomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectRoomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rid;
        
        public selectRoomRequestBody() {
        }
        
        public selectRoomRequestBody(string rid) {
            this.rid = rid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectRoomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectRoomResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.selectRoomResponseBody Body;
        
        public selectRoomResponse() {
        }
        
        public selectRoomResponse(Kt.GameGroup.Services.CharRoomService.selectRoomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectRoomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Kt.GameGroup.Services.CharRoomService.Room selectRoomResult;
        
        public selectRoomResponseBody() {
        }
        
        public selectRoomResponseBody(Kt.GameGroup.Services.CharRoomService.Room selectRoomResult) {
            this.selectRoomResult = selectRoomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectRoomByfIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectRoomByfId", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequestBody Body;
        
        public selectRoomByfIdRequest() {
        }
        
        public selectRoomByfIdRequest(Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectRoomByfIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string gid;
        
        public selectRoomByfIdRequestBody() {
        }
        
        public selectRoomByfIdRequestBody(string gid) {
            this.gid = gid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class selectRoomByfIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="selectRoomByfIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public Kt.GameGroup.Services.CharRoomService.selectRoomByfIdResponseBody Body;
        
        public selectRoomByfIdResponse() {
        }
        
        public selectRoomByfIdResponse(Kt.GameGroup.Services.CharRoomService.selectRoomByfIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class selectRoomByfIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Kt.GameGroup.Services.CharRoomService.ArrayOfAnyType selectRoomByfIdResult;
        
        public selectRoomByfIdResponseBody() {
        }
        
        public selectRoomByfIdResponseBody(Kt.GameGroup.Services.CharRoomService.ArrayOfAnyType selectRoomByfIdResult) {
            this.selectRoomByfIdResult = selectRoomByfIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface gameServiceSoapChannel : Kt.GameGroup.Services.CharRoomService.gameServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class gameServiceSoapClient : System.ServiceModel.ClientBase<Kt.GameGroup.Services.CharRoomService.gameServiceSoap>, Kt.GameGroup.Services.CharRoomService.gameServiceSoap {
        
        public gameServiceSoapClient() {
        }
        
        public gameServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public gameServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gameServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public gameServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kt.GameGroup.Services.CharRoomService.addRoomResponse Kt.GameGroup.Services.CharRoomService.gameServiceSoap.addRoom(Kt.GameGroup.Services.CharRoomService.addRoomRequest request) {
            return base.Channel.addRoom(request);
        }
        
        public int addRoom(string gid, string fid, string rname, string rpsw, string rmaxnum, string rtype, string rorder, string rmode) {
            Kt.GameGroup.Services.CharRoomService.addRoomRequest inValue = new Kt.GameGroup.Services.CharRoomService.addRoomRequest();
            inValue.Body = new Kt.GameGroup.Services.CharRoomService.addRoomRequestBody();
            inValue.Body.gid = gid;
            inValue.Body.fid = fid;
            inValue.Body.rname = rname;
            inValue.Body.rpsw = rpsw;
            inValue.Body.rmaxnum = rmaxnum;
            inValue.Body.rtype = rtype;
            inValue.Body.rorder = rorder;
            inValue.Body.rmode = rmode;
            Kt.GameGroup.Services.CharRoomService.addRoomResponse retVal = ((Kt.GameGroup.Services.CharRoomService.gameServiceSoap)(this)).addRoom(inValue);
            return retVal.Body.addRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kt.GameGroup.Services.CharRoomService.deleteRoomResponse Kt.GameGroup.Services.CharRoomService.gameServiceSoap.deleteRoom(Kt.GameGroup.Services.CharRoomService.deleteRoomRequest request) {
            return base.Channel.deleteRoom(request);
        }
        
        public int deleteRoom(string rid) {
            Kt.GameGroup.Services.CharRoomService.deleteRoomRequest inValue = new Kt.GameGroup.Services.CharRoomService.deleteRoomRequest();
            inValue.Body = new Kt.GameGroup.Services.CharRoomService.deleteRoomRequestBody();
            inValue.Body.rid = rid;
            Kt.GameGroup.Services.CharRoomService.deleteRoomResponse retVal = ((Kt.GameGroup.Services.CharRoomService.gameServiceSoap)(this)).deleteRoom(inValue);
            return retVal.Body.deleteRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kt.GameGroup.Services.CharRoomService.updateRoomResponse Kt.GameGroup.Services.CharRoomService.gameServiceSoap.updateRoom(Kt.GameGroup.Services.CharRoomService.updateRoomRequest request) {
            return base.Channel.updateRoom(request);
        }
        
        public int updateRoom(string rid, string rpsw, string rmaxnum, string rtype, string rorder, string rmode, string rname) {
            Kt.GameGroup.Services.CharRoomService.updateRoomRequest inValue = new Kt.GameGroup.Services.CharRoomService.updateRoomRequest();
            inValue.Body = new Kt.GameGroup.Services.CharRoomService.updateRoomRequestBody();
            inValue.Body.rid = rid;
            inValue.Body.rpsw = rpsw;
            inValue.Body.rmaxnum = rmaxnum;
            inValue.Body.rtype = rtype;
            inValue.Body.rorder = rorder;
            inValue.Body.rmode = rmode;
            inValue.Body.rname = rname;
            Kt.GameGroup.Services.CharRoomService.updateRoomResponse retVal = ((Kt.GameGroup.Services.CharRoomService.gameServiceSoap)(this)).updateRoom(inValue);
            return retVal.Body.updateRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kt.GameGroup.Services.CharRoomService.updateRoomInfoResponse Kt.GameGroup.Services.CharRoomService.gameServiceSoap.updateRoomInfo(Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequest request) {
            return base.Channel.updateRoomInfo(request);
        }
        
        public int updateRoomInfo(string rid, string rpsw, string rname, string rmembertype, string rmic, string rmictime, string rtextchat, string rchatspeed, string rtextwords) {
            Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequest inValue = new Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequest();
            inValue.Body = new Kt.GameGroup.Services.CharRoomService.updateRoomInfoRequestBody();
            inValue.Body.rid = rid;
            inValue.Body.rpsw = rpsw;
            inValue.Body.rname = rname;
            inValue.Body.rmembertype = rmembertype;
            inValue.Body.rmic = rmic;
            inValue.Body.rmictime = rmictime;
            inValue.Body.rtextchat = rtextchat;
            inValue.Body.rchatspeed = rchatspeed;
            inValue.Body.rtextwords = rtextwords;
            Kt.GameGroup.Services.CharRoomService.updateRoomInfoResponse retVal = ((Kt.GameGroup.Services.CharRoomService.gameServiceSoap)(this)).updateRoomInfo(inValue);
            return retVal.Body.updateRoomInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kt.GameGroup.Services.CharRoomService.selectRoomResponse Kt.GameGroup.Services.CharRoomService.gameServiceSoap.selectRoom(Kt.GameGroup.Services.CharRoomService.selectRoomRequest request) {
            return base.Channel.selectRoom(request);
        }
        
        public Kt.GameGroup.Services.CharRoomService.Room selectRoom(string rid) {
            Kt.GameGroup.Services.CharRoomService.selectRoomRequest inValue = new Kt.GameGroup.Services.CharRoomService.selectRoomRequest();
            inValue.Body = new Kt.GameGroup.Services.CharRoomService.selectRoomRequestBody();
            inValue.Body.rid = rid;
            Kt.GameGroup.Services.CharRoomService.selectRoomResponse retVal = ((Kt.GameGroup.Services.CharRoomService.gameServiceSoap)(this)).selectRoom(inValue);
            return retVal.Body.selectRoomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kt.GameGroup.Services.CharRoomService.selectRoomByfIdResponse Kt.GameGroup.Services.CharRoomService.gameServiceSoap.selectRoomByfId(Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequest request) {
            return base.Channel.selectRoomByfId(request);
        }
        
        public Kt.GameGroup.Services.CharRoomService.ArrayOfAnyType selectRoomByfId(string gid) {
            Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequest inValue = new Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequest();
            inValue.Body = new Kt.GameGroup.Services.CharRoomService.selectRoomByfIdRequestBody();
            inValue.Body.gid = gid;
            Kt.GameGroup.Services.CharRoomService.selectRoomByfIdResponse retVal = ((Kt.GameGroup.Services.CharRoomService.gameServiceSoap)(this)).selectRoomByfId(inValue);
            return retVal.Body.selectRoomByfIdResult;
        }
    }
}
