//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 关系源元数据

[assembly: EdmRelationshipAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbs", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kt.GameGroup.Data.group_bbs), "group_bbsReply", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kt.GameGroup.Data.group_bbsReply), true)]
[assembly: EdmRelationshipAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_IN", "group_Infor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kt.GameGroup.Data.group_Infor), "group_bbs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kt.GameGroup.Data.group_bbs), true)]
[assembly: EdmRelationshipAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_Infor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kt.GameGroup.Data.group_Infor), "group_bbsSort", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kt.GameGroup.Data.group_bbsSort), true)]
[assembly: EdmRelationshipAttribute("GameGroupModel", "FK_GROUP_ME_REFERENCE_GROUP_IN", "group_Infor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Kt.GameGroup.Data.group_Infor), "group_member", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Kt.GameGroup.Data.group_member), true)]

#endregion

namespace Kt.GameGroup.Data
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class GameGroupEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“GameGroupEntities”部分中的连接字符串初始化新 GameGroupEntities 对象。
        /// </summary>
        public GameGroupEntities() : base("name=GameGroupEntities", "GameGroupEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GameGroupEntities 对象。
        /// </summary>
        public GameGroupEntities(string connectionString) : base(connectionString, "GameGroupEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 GameGroupEntities 对象。
        /// </summary>
        public GameGroupEntities(EntityConnection connection) : base(connection, "GameGroupEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<group_bbs> group_bbs
        {
            get
            {
                if ((_group_bbs == null))
                {
                    _group_bbs = base.CreateObjectSet<group_bbs>("group_bbs");
                }
                return _group_bbs;
            }
        }
        private ObjectSet<group_bbs> _group_bbs;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<group_bbsReply> group_bbsReply
        {
            get
            {
                if ((_group_bbsReply == null))
                {
                    _group_bbsReply = base.CreateObjectSet<group_bbsReply>("group_bbsReply");
                }
                return _group_bbsReply;
            }
        }
        private ObjectSet<group_bbsReply> _group_bbsReply;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<group_bbsSort> group_bbsSort
        {
            get
            {
                if ((_group_bbsSort == null))
                {
                    _group_bbsSort = base.CreateObjectSet<group_bbsSort>("group_bbsSort");
                }
                return _group_bbsSort;
            }
        }
        private ObjectSet<group_bbsSort> _group_bbsSort;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<group_gameStat> group_gameStat
        {
            get
            {
                if ((_group_gameStat == null))
                {
                    _group_gameStat = base.CreateObjectSet<group_gameStat>("group_gameStat");
                }
                return _group_gameStat;
            }
        }
        private ObjectSet<group_gameStat> _group_gameStat;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Group_Grade> Group_Grade
        {
            get
            {
                if ((_Group_Grade == null))
                {
                    _Group_Grade = base.CreateObjectSet<Group_Grade>("Group_Grade");
                }
                return _Group_Grade;
            }
        }
        private ObjectSet<Group_Grade> _Group_Grade;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<group_Infor> group_Infor
        {
            get
            {
                if ((_group_Infor == null))
                {
                    _group_Infor = base.CreateObjectSet<group_Infor>("group_Infor");
                }
                return _group_Infor;
            }
        }
        private ObjectSet<group_Infor> _group_Infor;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<group_member> group_member
        {
            get
            {
                if ((_group_member == null))
                {
                    _group_member = base.CreateObjectSet<group_member>("group_member");
                }
                return _group_member;
            }
        }
        private ObjectSet<group_member> _group_member;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 group_bbs EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTogroup_bbs(group_bbs group_bbs)
        {
            base.AddObject("group_bbs", group_bbs);
        }
    
        /// <summary>
        /// 用于向 group_bbsReply EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTogroup_bbsReply(group_bbsReply group_bbsReply)
        {
            base.AddObject("group_bbsReply", group_bbsReply);
        }
    
        /// <summary>
        /// 用于向 group_bbsSort EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTogroup_bbsSort(group_bbsSort group_bbsSort)
        {
            base.AddObject("group_bbsSort", group_bbsSort);
        }
    
        /// <summary>
        /// 用于向 group_gameStat EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTogroup_gameStat(group_gameStat group_gameStat)
        {
            base.AddObject("group_gameStat", group_gameStat);
        }
    
        /// <summary>
        /// 用于向 Group_Grade EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToGroup_Grade(Group_Grade group_Grade)
        {
            base.AddObject("Group_Grade", group_Grade);
        }
    
        /// <summary>
        /// 用于向 group_Infor EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTogroup_Infor(group_Infor group_Infor)
        {
            base.AddObject("group_Infor", group_Infor);
        }
    
        /// <summary>
        /// 用于向 group_member EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTogroup_member(group_member group_member)
        {
            base.AddObject("group_member", group_member);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="group_bbs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_bbs : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 group_bbs 对象。
        /// </summary>
        /// <param name="bbsId">bbsId 属性的初始值。</param>
        /// <param name="postSortId">postSortId 属性的初始值。</param>
        /// <param name="isAudit">isAudit 属性的初始值。</param>
        public static group_bbs Creategroup_bbs(global::System.Int32 bbsId, global::System.Int32 postSortId, global::System.Boolean isAudit)
        {
            group_bbs group_bbs = new group_bbs();
            group_bbs.bbsId = bbsId;
            group_bbs.postSortId = postSortId;
            group_bbs.isAudit = isAudit;
            return group_bbs;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 bbsId
        {
            get
            {
                return _bbsId;
            }
            set
            {
                if (_bbsId != value)
                {
                    OnbbsIdChanging(value);
                    ReportPropertyChanging("bbsId");
                    _bbsId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("bbsId");
                    OnbbsIdChanged();
                }
            }
        }
        private global::System.Int32 _bbsId;
        partial void OnbbsIdChanging(global::System.Int32 value);
        partial void OnbbsIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gId
        {
            get
            {
                return _gId;
            }
            set
            {
                OngIdChanging(value);
                ReportPropertyChanging("gId");
                _gId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gId");
                OngIdChanged();
            }
        }
        private Nullable<global::System.Int32> _gId;
        partial void OngIdChanging(Nullable<global::System.Int32> value);
        partial void OngIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 postSortId
        {
            get
            {
                return _postSortId;
            }
            set
            {
                OnpostSortIdChanging(value);
                ReportPropertyChanging("postSortId");
                _postSortId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("postSortId");
                OnpostSortIdChanged();
            }
        }
        private global::System.Int32 _postSortId;
        partial void OnpostSortIdChanging(global::System.Int32 value);
        partial void OnpostSortIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> publishId
        {
            get
            {
                return _publishId;
            }
            set
            {
                OnpublishIdChanging(value);
                ReportPropertyChanging("publishId");
                _publishId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("publishId");
                OnpublishIdChanged();
            }
        }
        private Nullable<global::System.Int32> _publishId;
        partial void OnpublishIdChanging(Nullable<global::System.Int32> value);
        partial void OnpublishIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> uId
        {
            get
            {
                return _uId;
            }
            set
            {
                OnuIdChanging(value);
                ReportPropertyChanging("uId");
                _uId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uId");
                OnuIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _uId;
        partial void OnuIdChanging(Nullable<global::System.Decimal> value);
        partial void OnuIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> sendTime
        {
            get
            {
                return _sendTime;
            }
            set
            {
                OnsendTimeChanging(value);
                ReportPropertyChanging("sendTime");
                _sendTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sendTime");
                OnsendTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _sendTime;
        partial void OnsendTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnsendTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nickName
        {
            get
            {
                return _nickName;
            }
            set
            {
                OnnickNameChanging(value);
                ReportPropertyChanging("nickName");
                _nickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nickName");
                OnnickNameChanged();
            }
        }
        private global::System.String _nickName;
        partial void OnnickNameChanging(global::System.String value);
        partial void OnnickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> replyNum
        {
            get
            {
                return _replyNum;
            }
            set
            {
                OnreplyNumChanging(value);
                ReportPropertyChanging("replyNum");
                _replyNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("replyNum");
                OnreplyNumChanged();
            }
        }
        private Nullable<global::System.Int32> _replyNum;
        partial void OnreplyNumChanging(Nullable<global::System.Int32> value);
        partial void OnreplyNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> clickNum
        {
            get
            {
                return _clickNum;
            }
            set
            {
                OnclickNumChanging(value);
                ReportPropertyChanging("clickNum");
                _clickNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clickNum");
                OnclickNumChanged();
            }
        }
        private Nullable<global::System.Int32> _clickNum;
        partial void OnclickNumChanging(Nullable<global::System.Int32> value);
        partial void OnclickNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> lastUid
        {
            get
            {
                return _lastUid;
            }
            set
            {
                OnlastUidChanging(value);
                ReportPropertyChanging("lastUid");
                _lastUid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastUid");
                OnlastUidChanged();
            }
        }
        private Nullable<global::System.Decimal> _lastUid;
        partial void OnlastUidChanging(Nullable<global::System.Decimal> value);
        partial void OnlastUidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String lastNickName
        {
            get
            {
                return _lastNickName;
            }
            set
            {
                OnlastNickNameChanging(value);
                ReportPropertyChanging("lastNickName");
                _lastNickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("lastNickName");
                OnlastNickNameChanged();
            }
        }
        private global::System.String _lastNickName;
        partial void OnlastNickNameChanging(global::System.String value);
        partial void OnlastNickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> lastTime
        {
            get
            {
                return _lastTime;
            }
            set
            {
                OnlastTimeChanging(value);
                ReportPropertyChanging("lastTime");
                _lastTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("lastTime");
                OnlastTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _lastTime;
        partial void OnlastTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnlastTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isTop
        {
            get
            {
                return _isTop;
            }
            set
            {
                OnisTopChanging(value);
                ReportPropertyChanging("isTop");
                _isTop = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isTop");
                OnisTopChanged();
            }
        }
        private Nullable<global::System.Boolean> _isTop;
        partial void OnisTopChanging(Nullable<global::System.Boolean> value);
        partial void OnisTopChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isLight
        {
            get
            {
                return _isLight;
            }
            set
            {
                OnisLightChanging(value);
                ReportPropertyChanging("isLight");
                _isLight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isLight");
                OnisLightChanged();
            }
        }
        private Nullable<global::System.Boolean> _isLight;
        partial void OnisLightChanging(Nullable<global::System.Boolean> value);
        partial void OnisLightChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isPith
        {
            get
            {
                return _isPith;
            }
            set
            {
                OnisPithChanging(value);
                ReportPropertyChanging("isPith");
                _isPith = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPith");
                OnisPithChanged();
            }
        }
        private Nullable<global::System.Boolean> _isPith;
        partial void OnisPithChanging(Nullable<global::System.Boolean> value);
        partial void OnisPithChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean isAudit
        {
            get
            {
                return _isAudit;
            }
            set
            {
                OnisAuditChanging(value);
                ReportPropertyChanging("isAudit");
                _isAudit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isAudit");
                OnisAuditChanged();
            }
        }
        private global::System.Boolean _isAudit;
        partial void OnisAuditChanging(global::System.Boolean value);
        partial void OnisAuditChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbsReply")]
        public EntityCollection<group_bbsReply> group_bbsReply
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<group_bbsReply>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbsReply");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<group_bbsReply>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbsReply", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_IN", "group_Infor")]
        public group_Infor group_Infor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN", "group_Infor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN", "group_Infor").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<group_Infor> group_InforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN", "group_Infor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN", "group_Infor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="group_bbsReply")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_bbsReply : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 group_bbsReply 对象。
        /// </summary>
        /// <param name="replyId">replyId 属性的初始值。</param>
        public static group_bbsReply Creategroup_bbsReply(global::System.Int32 replyId)
        {
            group_bbsReply group_bbsReply = new group_bbsReply();
            group_bbsReply.replyId = replyId;
            return group_bbsReply;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 replyId
        {
            get
            {
                return _replyId;
            }
            set
            {
                if (_replyId != value)
                {
                    OnreplyIdChanging(value);
                    ReportPropertyChanging("replyId");
                    _replyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("replyId");
                    OnreplyIdChanged();
                }
            }
        }
        private global::System.Int32 _replyId;
        partial void OnreplyIdChanging(global::System.Int32 value);
        partial void OnreplyIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> bbsId
        {
            get
            {
                return _bbsId;
            }
            set
            {
                OnbbsIdChanging(value);
                ReportPropertyChanging("bbsId");
                _bbsId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("bbsId");
                OnbbsIdChanged();
            }
        }
        private Nullable<global::System.Int32> _bbsId;
        partial void OnbbsIdChanging(Nullable<global::System.Int32> value);
        partial void OnbbsIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> uId
        {
            get
            {
                return _uId;
            }
            set
            {
                OnuIdChanging(value);
                ReportPropertyChanging("uId");
                _uId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uId");
                OnuIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _uId;
        partial void OnuIdChanging(Nullable<global::System.Decimal> value);
        partial void OnuIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nickName
        {
            get
            {
                return _nickName;
            }
            set
            {
                OnnickNameChanging(value);
                ReportPropertyChanging("nickName");
                _nickName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nickName");
                OnnickNameChanged();
            }
        }
        private global::System.String _nickName;
        partial void OnnickNameChanging(global::System.String value);
        partial void OnnickNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> repTime
        {
            get
            {
                return _repTime;
            }
            set
            {
                OnrepTimeChanging(value);
                ReportPropertyChanging("repTime");
                _repTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("repTime");
                OnrepTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _repTime;
        partial void OnrepTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrepTimeChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbs")]
        public group_bbs group_bbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_bbs>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_bbs>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbs").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<group_bbs> group_bbsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_bbs>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<group_bbs>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_BB_xx", "group_bbs", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="group_bbsSort")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_bbsSort : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 group_bbsSort 对象。
        /// </summary>
        /// <param name="sortId">sortId 属性的初始值。</param>
        public static group_bbsSort Creategroup_bbsSort(global::System.Int32 sortId)
        {
            group_bbsSort group_bbsSort = new group_bbsSort();
            group_bbsSort.sortId = sortId;
            return group_bbsSort;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sortId
        {
            get
            {
                return _sortId;
            }
            set
            {
                if (_sortId != value)
                {
                    OnsortIdChanging(value);
                    ReportPropertyChanging("sortId");
                    _sortId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sortId");
                    OnsortIdChanged();
                }
            }
        }
        private global::System.Int32 _sortId;
        partial void OnsortIdChanging(global::System.Int32 value);
        partial void OnsortIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gId
        {
            get
            {
                return _gId;
            }
            set
            {
                OngIdChanging(value);
                ReportPropertyChanging("gId");
                _gId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gId");
                OngIdChanged();
            }
        }
        private Nullable<global::System.Int32> _gId;
        partial void OngIdChanging(Nullable<global::System.Int32> value);
        partial void OngIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> showXh
        {
            get
            {
                return _showXh;
            }
            set
            {
                OnshowXhChanging(value);
                ReportPropertyChanging("showXh");
                _showXh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("showXh");
                OnshowXhChanged();
            }
        }
        private Nullable<global::System.Int32> _showXh;
        partial void OnshowXhChanging(Nullable<global::System.Int32> value);
        partial void OnshowXhChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sortName
        {
            get
            {
                return _sortName;
            }
            set
            {
                OnsortNameChanging(value);
                ReportPropertyChanging("sortName");
                _sortName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sortName");
                OnsortNameChanged();
            }
        }
        private global::System.String _sortName;
        partial void OnsortNameChanging(global::System.String value);
        partial void OnsortNameChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_Infor")]
        public group_Infor group_Infor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_Infor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_Infor").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<group_Infor> group_InforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_Infor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_Infor", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="group_gameStat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_gameStat : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 group_gameStat 对象。
        /// </summary>
        /// <param name="gameId">gameId 属性的初始值。</param>
        public static group_gameStat Creategroup_gameStat(global::System.Int32 gameId)
        {
            group_gameStat group_gameStat = new group_gameStat();
            group_gameStat.gameId = gameId;
            return group_gameStat;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gameId
        {
            get
            {
                return _gameId;
            }
            set
            {
                if (_gameId != value)
                {
                    OngameIdChanging(value);
                    ReportPropertyChanging("gameId");
                    _gameId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("gameId");
                    OngameIdChanged();
                }
            }
        }
        private global::System.Int32 _gameId;
        partial void OngameIdChanging(global::System.Int32 value);
        partial void OngameIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> groupNum
        {
            get
            {
                return _groupNum;
            }
            set
            {
                OngroupNumChanging(value);
                ReportPropertyChanging("groupNum");
                _groupNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupNum");
                OngroupNumChanged();
            }
        }
        private Nullable<global::System.Int32> _groupNum;
        partial void OngroupNumChanging(Nullable<global::System.Int32> value);
        partial void OngroupNumChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="Group_Grade")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Group_Grade : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Group_Grade 对象。
        /// </summary>
        /// <param name="autoId">AutoId 属性的初始值。</param>
        /// <param name="gid">Gid 属性的初始值。</param>
        /// <param name="gradeId">GradeId 属性的初始值。</param>
        /// <param name="gradeName">GradeName 属性的初始值。</param>
        public static Group_Grade CreateGroup_Grade(global::System.Int32 autoId, global::System.Int32 gid, global::System.Int32 gradeId, global::System.String gradeName)
        {
            Group_Grade group_Grade = new Group_Grade();
            group_Grade.AutoId = autoId;
            group_Grade.Gid = gid;
            group_Grade.GradeId = gradeId;
            group_Grade.GradeName = gradeName;
            return group_Grade;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AutoId
        {
            get
            {
                return _AutoId;
            }
            set
            {
                if (_AutoId != value)
                {
                    OnAutoIdChanging(value);
                    ReportPropertyChanging("AutoId");
                    _AutoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("AutoId");
                    OnAutoIdChanged();
                }
            }
        }
        private global::System.Int32 _AutoId;
        partial void OnAutoIdChanging(global::System.Int32 value);
        partial void OnAutoIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Gid
        {
            get
            {
                return _Gid;
            }
            set
            {
                OnGidChanging(value);
                ReportPropertyChanging("Gid");
                _Gid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gid");
                OnGidChanged();
            }
        }
        private global::System.Int32 _Gid;
        partial void OnGidChanging(global::System.Int32 value);
        partial void OnGidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GradeId
        {
            get
            {
                return _GradeId;
            }
            set
            {
                OnGradeIdChanging(value);
                ReportPropertyChanging("GradeId");
                _GradeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GradeId");
                OnGradeIdChanged();
            }
        }
        private global::System.Int32 _GradeId;
        partial void OnGradeIdChanging(global::System.Int32 value);
        partial void OnGradeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GradeName
        {
            get
            {
                return _GradeName;
            }
            set
            {
                OnGradeNameChanging(value);
                ReportPropertyChanging("GradeName");
                _GradeName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GradeName");
                OnGradeNameChanged();
            }
        }
        private global::System.String _GradeName;
        partial void OnGradeNameChanging(global::System.String value);
        partial void OnGradeNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="group_Infor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_Infor : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 group_Infor 对象。
        /// </summary>
        /// <param name="gId">gId 属性的初始值。</param>
        public static group_Infor Creategroup_Infor(global::System.Int32 gId)
        {
            group_Infor group_Infor = new group_Infor();
            group_Infor.gId = gId;
            return group_Infor;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gId
        {
            get
            {
                return _gId;
            }
            set
            {
                if (_gId != value)
                {
                    OngIdChanging(value);
                    ReportPropertyChanging("gId");
                    _gId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("gId");
                    OngIdChanged();
                }
            }
        }
        private global::System.Int32 _gId;
        partial void OngIdChanging(global::System.Int32 value);
        partial void OngIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> uId
        {
            get
            {
                return _uId;
            }
            set
            {
                OnuIdChanging(value);
                ReportPropertyChanging("uId");
                _uId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uId");
                OnuIdChanged();
            }
        }
        private Nullable<global::System.Decimal> _uId;
        partial void OnuIdChanging(Nullable<global::System.Decimal> value);
        partial void OnuIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gName
        {
            get
            {
                return _gName;
            }
            set
            {
                OngNameChanging(value);
                ReportPropertyChanging("gName");
                _gName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gName");
                OngNameChanged();
            }
        }
        private global::System.String _gName;
        partial void OngNameChanging(global::System.String value);
        partial void OngNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> memberNum
        {
            get
            {
                return _memberNum;
            }
            set
            {
                OnmemberNumChanging(value);
                ReportPropertyChanging("memberNum");
                _memberNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("memberNum");
                OnmemberNumChanged();
            }
        }
        private Nullable<global::System.Int32> _memberNum;
        partial void OnmemberNumChanging(Nullable<global::System.Int32> value);
        partial void OnmemberNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> maxNum
        {
            get
            {
                return _maxNum;
            }
            set
            {
                OnmaxNumChanging(value);
                ReportPropertyChanging("maxNum");
                _maxNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("maxNum");
                OnmaxNumChanged();
            }
        }
        private Nullable<global::System.Int32> _maxNum;
        partial void OnmaxNumChanging(Nullable<global::System.Int32> value);
        partial void OnmaxNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> postNum
        {
            get
            {
                return _postNum;
            }
            set
            {
                OnpostNumChanging(value);
                ReportPropertyChanging("postNum");
                _postNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("postNum");
                OnpostNumChanged();
            }
        }
        private Nullable<global::System.Int32> _postNum;
        partial void OnpostNumChanging(Nullable<global::System.Int32> value);
        partial void OnpostNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> points
        {
            get
            {
                return _points;
            }
            set
            {
                OnpointsChanging(value);
                ReportPropertyChanging("points");
                _points = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("points");
                OnpointsChanged();
            }
        }
        private Nullable<global::System.Int32> _points;
        partial void OnpointsChanging(Nullable<global::System.Int32> value);
        partial void OnpointsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String account
        {
            get
            {
                return _account;
            }
            set
            {
                OnaccountChanging(value);
                ReportPropertyChanging("account");
                _account = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("account");
                OnaccountChanged();
            }
        }
        private global::System.String _account;
        partial void OnaccountChanging(global::System.String value);
        partial void OnaccountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String notice
        {
            get
            {
                return _notice;
            }
            set
            {
                OnnoticeChanging(value);
                ReportPropertyChanging("notice");
                _notice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("notice");
                OnnoticeChanged();
            }
        }
        private global::System.String _notice;
        partial void OnnoticeChanging(global::System.String value);
        partial void OnnoticeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gPic
        {
            get
            {
                return _gPic;
            }
            set
            {
                OngPicChanging(value);
                ReportPropertyChanging("gPic");
                _gPic = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("gPic");
                OngPicChanged();
            }
        }
        private global::System.String _gPic;
        partial void OngPicChanging(global::System.String value);
        partial void OngPicChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gameId
        {
            get
            {
                return _gameId;
            }
            set
            {
                OngameIdChanging(value);
                ReportPropertyChanging("gameId");
                _gameId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gameId");
                OngameIdChanged();
            }
        }
        private Nullable<global::System.Int32> _gameId;
        partial void OngameIdChanging(Nullable<global::System.Int32> value);
        partial void OngameIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> platFormId
        {
            get
            {
                return _platFormId;
            }
            set
            {
                OnplatFormIdChanging(value);
                ReportPropertyChanging("platFormId");
                _platFormId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("platFormId");
                OnplatFormIdChanged();
            }
        }
        private Nullable<global::System.Int32> _platFormId;
        partial void OnplatFormIdChanging(Nullable<global::System.Int32> value);
        partial void OnplatFormIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gameserverid
        {
            get
            {
                return _gameserverid;
            }
            set
            {
                OngameserveridChanging(value);
                ReportPropertyChanging("gameserverid");
                _gameserverid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gameserverid");
                OngameserveridChanged();
            }
        }
        private Nullable<global::System.Int32> _gameserverid;
        partial void OngameserveridChanging(Nullable<global::System.Int32> value);
        partial void OngameserveridChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> joinPerm
        {
            get
            {
                return _joinPerm;
            }
            set
            {
                OnjoinPermChanging(value);
                ReportPropertyChanging("joinPerm");
                _joinPerm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("joinPerm");
                OnjoinPermChanged();
            }
        }
        private Nullable<global::System.Int32> _joinPerm;
        partial void OnjoinPermChanging(Nullable<global::System.Int32> value);
        partial void OnjoinPermChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> viewPerm
        {
            get
            {
                return _viewPerm;
            }
            set
            {
                OnviewPermChanging(value);
                ReportPropertyChanging("viewPerm");
                _viewPerm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewPerm");
                OnviewPermChanged();
            }
        }
        private Nullable<global::System.Boolean> _viewPerm;
        partial void OnviewPermChanging(Nullable<global::System.Boolean> value);
        partial void OnviewPermChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> postPerm
        {
            get
            {
                return _postPerm;
            }
            set
            {
                OnpostPermChanging(value);
                ReportPropertyChanging("postPerm");
                _postPerm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("postPerm");
                OnpostPermChanged();
            }
        }
        private Nullable<global::System.Boolean> _postPerm;
        partial void OnpostPermChanging(Nullable<global::System.Boolean> value);
        partial void OnpostPermChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> recommend
        {
            get
            {
                return _recommend;
            }
            set
            {
                OnrecommendChanging(value);
                ReportPropertyChanging("recommend");
                _recommend = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("recommend");
                OnrecommendChanged();
            }
        }
        private Nullable<global::System.Boolean> _recommend;
        partial void OnrecommendChanging(Nullable<global::System.Boolean> value);
        partial void OnrecommendChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String reserve
        {
            get
            {
                return _reserve;
            }
            set
            {
                OnreserveChanging(value);
                ReportPropertyChanging("reserve");
                _reserve = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("reserve");
                OnreserveChanged();
            }
        }
        private global::System.String _reserve;
        partial void OnreserveChanging(global::System.String value);
        partial void OnreserveChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createDate
        {
            get
            {
                return _createDate;
            }
            set
            {
                OncreateDateChanging(value);
                ReportPropertyChanging("createDate");
                _createDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createDate");
                OncreateDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createDate;
        partial void OncreateDateChanging(Nullable<global::System.DateTime> value);
        partial void OncreateDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vistUrl
        {
            get
            {
                return _vistUrl;
            }
            set
            {
                OnvistUrlChanging(value);
                ReportPropertyChanging("vistUrl");
                _vistUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vistUrl");
                OnvistUrlChanged();
            }
        }
        private global::System.String _vistUrl;
        partial void OnvistUrlChanging(global::System.String value);
        partial void OnvistUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isOpenSort
        {
            get
            {
                return _isOpenSort;
            }
            set
            {
                OnisOpenSortChanging(value);
                ReportPropertyChanging("isOpenSort");
                _isOpenSort = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isOpenSort");
                OnisOpenSortChanged();
            }
        }
        private Nullable<global::System.Boolean> _isOpenSort;
        partial void OnisOpenSortChanging(Nullable<global::System.Boolean> value);
        partial void OnisOpenSortChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isClass
        {
            get
            {
                return _isClass;
            }
            set
            {
                OnisClassChanging(value);
                ReportPropertyChanging("isClass");
                _isClass = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isClass");
                OnisClassChanged();
            }
        }
        private Nullable<global::System.Boolean> _isClass;
        partial void OnisClassChanging(Nullable<global::System.Boolean> value);
        partial void OnisClassChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isPrefix
        {
            get
            {
                return _isPrefix;
            }
            set
            {
                OnisPrefixChanging(value);
                ReportPropertyChanging("isPrefix");
                _isPrefix = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isPrefix");
                OnisPrefixChanged();
            }
        }
        private Nullable<global::System.Boolean> _isPrefix;
        partial void OnisPrefixChanging(Nullable<global::System.Boolean> value);
        partial void OnisPrefixChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> isChatRoom
        {
            get
            {
                return _isChatRoom;
            }
            set
            {
                OnisChatRoomChanging(value);
                ReportPropertyChanging("isChatRoom");
                _isChatRoom = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isChatRoom");
                OnisChatRoomChanged();
            }
        }
        private Nullable<global::System.Int32> _isChatRoom;
        partial void OnisChatRoomChanging(Nullable<global::System.Int32> value);
        partial void OnisChatRoomChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_IN", "group_bbs")]
        public EntityCollection<group_bbs> group_bbs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<group_bbs>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN", "group_bbs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<group_bbs>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN", "group_bbs", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_bbsSort")]
        public EntityCollection<group_bbsSort> group_bbsSort
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<group_bbsSort>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_bbsSort");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<group_bbsSort>("GameGroupModel.FK_GROUP_BB_REFERENCE_GROUP_IN_1", "group_bbsSort", value);
                }
            }
        }
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_ME_REFERENCE_GROUP_IN", "group_member")]
        public EntityCollection<group_member> group_member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<group_member>("GameGroupModel.FK_GROUP_ME_REFERENCE_GROUP_IN", "group_member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<group_member>("GameGroupModel.FK_GROUP_ME_REFERENCE_GROUP_IN", "group_member", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GameGroupModel", Name="group_member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class group_member : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 group_member 对象。
        /// </summary>
        /// <param name="autoId">autoId 属性的初始值。</param>
        /// <param name="postNum">postNum 属性的初始值。</param>
        /// <param name="gradeId">GradeId 属性的初始值。</param>
        public static group_member Creategroup_member(global::System.Int32 autoId, global::System.Int32 postNum, global::System.Int32 gradeId)
        {
            group_member group_member = new group_member();
            group_member.autoId = autoId;
            group_member.postNum = postNum;
            group_member.GradeId = gradeId;
            return group_member;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 autoId
        {
            get
            {
                return _autoId;
            }
            set
            {
                if (_autoId != value)
                {
                    OnautoIdChanging(value);
                    ReportPropertyChanging("autoId");
                    _autoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("autoId");
                    OnautoIdChanged();
                }
            }
        }
        private global::System.Int32 _autoId;
        partial void OnautoIdChanging(global::System.Int32 value);
        partial void OnautoIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> myUid
        {
            get
            {
                return _myUid;
            }
            set
            {
                OnmyUidChanging(value);
                ReportPropertyChanging("myUid");
                _myUid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("myUid");
                OnmyUidChanged();
            }
        }
        private Nullable<global::System.Decimal> _myUid;
        partial void OnmyUidChanging(Nullable<global::System.Decimal> value);
        partial void OnmyUidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> uType
        {
            get
            {
                return _uType;
            }
            set
            {
                OnuTypeChanging(value);
                ReportPropertyChanging("uType");
                _uType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("uType");
                OnuTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _uType;
        partial void OnuTypeChanging(Nullable<global::System.Int32> value);
        partial void OnuTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gId
        {
            get
            {
                return _gId;
            }
            set
            {
                OngIdChanging(value);
                ReportPropertyChanging("gId");
                _gId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gId");
                OngIdChanged();
            }
        }
        private Nullable<global::System.Int32> _gId;
        partial void OngIdChanging(Nullable<global::System.Int32> value);
        partial void OngIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> state
        {
            get
            {
                return _state;
            }
            set
            {
                OnstateChanging(value);
                ReportPropertyChanging("state");
                _state = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("state");
                OnstateChanged();
            }
        }
        private Nullable<global::System.Boolean> _state;
        partial void OnstateChanging(Nullable<global::System.Boolean> value);
        partial void OnstateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> revTime
        {
            get
            {
                return _revTime;
            }
            set
            {
                OnrevTimeChanging(value);
                ReportPropertyChanging("revTime");
                _revTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("revTime");
                OnrevTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _revTime;
        partial void OnrevTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrevTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 postNum
        {
            get
            {
                return _postNum;
            }
            set
            {
                OnpostNumChanging(value);
                ReportPropertyChanging("postNum");
                _postNum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("postNum");
                OnpostNumChanged();
            }
        }
        private global::System.Int32 _postNum;
        partial void OnpostNumChanging(global::System.Int32 value);
        partial void OnpostNumChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastPostTime
        {
            get
            {
                return _LastPostTime;
            }
            set
            {
                OnLastPostTimeChanging(value);
                ReportPropertyChanging("LastPostTime");
                _LastPostTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastPostTime");
                OnLastPostTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastPostTime;
        partial void OnLastPostTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnLastPostTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GradeId
        {
            get
            {
                return _GradeId;
            }
            set
            {
                OnGradeIdChanging(value);
                ReportPropertyChanging("GradeId");
                _GradeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GradeId");
                OnGradeIdChanged();
            }
        }
        private global::System.Int32 _GradeId;
        partial void OnGradeIdChanging(global::System.Int32 value);
        partial void OnGradeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupUserName
        {
            get
            {
                return _GroupUserName;
            }
            set
            {
                OnGroupUserNameChanging(value);
                ReportPropertyChanging("GroupUserName");
                _GroupUserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupUserName");
                OnGroupUserNameChanged();
            }
        }
        private global::System.String _GroupUserName;
        partial void OnGroupUserNameChanging(global::System.String value);
        partial void OnGroupUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String GroupUserImg
        {
            get
            {
                return _GroupUserImg;
            }
            set
            {
                OnGroupUserImgChanging(value);
                ReportPropertyChanging("GroupUserImg");
                _GroupUserImg = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("GroupUserImg");
                OnGroupUserImgChanged();
            }
        }
        private global::System.String _GroupUserImg;
        partial void OnGroupUserImgChanging(global::System.String value);
        partial void OnGroupUserImgChanged();

        #endregion
    
        #region 导航属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GameGroupModel", "FK_GROUP_ME_REFERENCE_GROUP_IN", "group_Infor")]
        public group_Infor group_Infor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_ME_REFERENCE_GROUP_IN", "group_Infor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_ME_REFERENCE_GROUP_IN", "group_Infor").Value = value;
            }
        }
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<group_Infor> group_InforReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_ME_REFERENCE_GROUP_IN", "group_Infor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<group_Infor>("GameGroupModel.FK_GROUP_ME_REFERENCE_GROUP_IN", "group_Infor", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
